import Head from "next/head";
import React, { FunctionComponent, ReactNode } from "react";

type RootLayoutProps = {
  children?: ReactNode;
};

const RootLayout: FunctionComponent<RootLayoutProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Comments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  );
};

export default RootLayout;
