import { Dispatch } from '@rematch/store'
import Head from 'next/head'
import { FunctionComponent, ReactNode, useEffect } from 'react'
import { useDispatch } from 'react-redux'

type RootLayoutProps = {
  children?: ReactNode
}

const RootLayout: FunctionComponent<RootLayoutProps> = ({ children }) => {
  const dispatch = useDispatch<Dispatch>()

  useEffect(() => {
    dispatch.comments.loadComments()
  }, [dispatch.comments])

  return (
    <div>
      <Head>
        <title>Comments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  )
}

export default RootLayout
